### ISSUE TITLE
Number format error while converting empty string json to Integer

### ISSUE THREAD

**Issue by m0mus** [eclipse/yasson#3]
From json to Object throws number format error if numeric field value is supplied in empty quotes.

for example in the front end
JSON.stringify(products) converts the json to empty quoted string

in the server side , this code throws numberformat error
jsonb.fromJson("{"id":"","productName":"test"}", Product.class);

 java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.eclipse.persistence.json.bind.internal.serializer.IntegerTypeDeserializer.lambda$deserialize$58(IntegerTypeDeserializer.java:34)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.eclipse.persistence.json.bind.internal.serializer.IntegerTypeDeserializer.deserialize(IntegerTypeDeserializer.java:34)
	at org.eclipse.persistence.json.bind.internal.serializer.IntegerTypeDeserializer.deserialize(IntegerTypeDeserializer.java:25)
	at org.eclipse.persistence.json.bind.internal.serializer.AbstractValueTypeDeserializer.deserialize(AbstractValueTypeDeserializer.java:61)
	at org.eclipse.persistence.json.bind.internal.unmarshaller.ObjectDeserializer.deserializeNext(ObjectDeserializer.java:142)
	at org.eclipse.persistence.json.bind.internal.unmarshaller.AbstractContainerDeserializer.deserializeInternal(AbstractContainerDeserializer.java:74)
	at org.eclipse.persistence.json.bind.internal.unmarshaller.AbstractContainerDeserializer.deserialize(AbstractContainerDeserializer.java:55)
	at org.eclipse.persistence.json.bind.internal.unmarshaller.CollectionDeserializer.deserializeNext(CollectionDeserializer.java:118)
	at org.eclipse.persistence.json.bind.internal.unmarshaller.AbstractContainerDeserializer.deserializeInternal(AbstractContainerDeserializer.java:74)
	at org.eclipse.persistence.json.bind.internal.unmarshaller.AbstractContainerDeserializer.deserialize(AbstractContainerDeserializer.java:55)
	at org.eclipse.persistence.json.bind.internal.Unmarshaller.deserializeItem(Unmarshaller.java:57)
	at org.eclipse.persistence.json.bind.internal.Unmarshaller.deserialize(Unmarshaller.java:50)

**Comment by m0mus** [comment]
This issue was submitted to JSON-B specification issue tracker, but more related to Yasson, so I am reposting it here.

According to the spec, number values in json document represented without quotes. If quotes are there it's a string value. This is why you have a binding exception. 
I see a problem here in the exception type. I suppose that JsonbException has to be thrown here, not NumberFormatException.

**Comment by moghaddam** [comment]
@m0mus I've found the root cause of the issue. I started with the IntegerTypeDeserializer (the same issue exits for Double, Float, etc). I just want to know which message should we use for this scenario? is it ok to reuse the MessageKeys.DESERIALIZE_VALUE_ERROR key that is "**Error deserialize JSON value into type: {}**" or you prefer to define a new key for this scenario. I tested it with Integer.class as a parameter and the final output is something like this:
**Error deserialize JSON value into type: java.lang.Integer**

In the context that this exception happens, we have access to the JsonBindingModel instance from which we can get the property name. So it would be more helpful for developers to know exactly what property goes wrong. Maybe we can provide a more detailed message like this:

"Error deserializing JSON value of property '{}' into type {}" (e.g. Error deserializing JSON value of property 'age' into type java.lang.Integer)

**Comment by m0mus** [comment]
I think it's OK to reuse MessageKeys.DESERIALIZE_VALUE_ERROR message.

**Comment by moghaddam** [comment]
OK. I'm trying to develop some unit tests for this scenario. We need to have some Java Beans to test basic serialization/deserialization scenarios. There is a class named GenericTestClass that seems to be a shortcut to prevent creating such Java Beans. But I think it would not be possible to test all scenarios using this technique due to type erasure process at compile time (specifically for deserializtion process). Also some issues happens only when a property is primitive/boxed type.
Do you think it would be OK to have such Java Beans (e.g. in org.eclipse.yasson.defaultmapping.basic.model package) like the one we already have for testing boolean (BooleanModel)?

**Comment by bravehorsie** [comment]
"model" subpackage for various tests is used to create bean test classes for tests. If you need other bean classes for tests feel free to create those, or modify existing. Type erasure is why there is optional "Type" argument in fromJson/toJson methods. If you use it, runtime is aware of what type is TypeVariable inside GenericTestClass.

**Comment by moghaddam** [comment]
You're right @bravehorsie :wink: It works in my scenario too. I just updated unmarshaller classes for all numeric types and added a test for each one

**Comment by m0mus** [comment]
Fixed and pushed to master.
