### ISSUE TITLE
new ArrayList<Dog>(){}.getClass()); not working in example, is giving exception

### ISSUE THREAD

**Issue by ullenboom** [eclipse/yasson#31]
Here is my example:

```
package com.tutego.insel.json;

import java.util.ArrayList;
import java.util.List;
import javax.json.bind.Jsonb;
import javax.json.bind.JsonbBuilder;

public class Dog {
  public String name;
  public int age;
  public boolean bitable;

  public static void main( String[] args ) {
    // Create a dog instance
    Dog falco = new Dog();
    falco.name = "Falco";
    falco.age = 4;
    falco.bitable = false;

    Dog cassidy = new Dog();

    List<Dog> dogs = new ArrayList<>();
    dogs.add( falco );
    dogs.add( cassidy );

    // Create Jsonb and serialize
    Jsonb jsonb = JsonbBuilder.create();
    String result = jsonb.toJson( dogs );
    System.out.println( result );

    // Deserialize back
    dogs = jsonb.fromJson( result, new ArrayList<Dog>() { }.getClass() );

  }
}

```
This will give:

```
[{"age":4,"bitable":false,"name":"Falco"},{"age":0,"bitable":false}]
Exception in thread "main" javax.json.bind.JsonbException: Can't create instance
	at org.eclipse.yasson.internal.ReflectionUtils.lambda$createNoArgConstructorInstance$1(ReflectionUtils.java:191)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.yasson.internal.ReflectionUtils.createNoArgConstructorInstance(ReflectionUtils.java:186)
	at org.eclipse.yasson.internal.serializer.CollectionDeserializer.createInstance(CollectionDeserializer.java:71)
	at org.eclipse.yasson.internal.serializer.CollectionDeserializer.<init>(CollectionDeserializer.java:53)
	at org.eclipse.yasson.internal.serializer.DeserializerBuilder.build(DeserializerBuilder.java:126)
	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:56)
	at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:50)
	at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:45)
	at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:52)
	at com.tutego.insel.json.Dog.main(Dog.java:32)
Caused by: java.lang.IllegalAccessException: Class org.eclipse.yasson.internal.ReflectionUtils can not access a member of class com.tutego.insel.json.Dog$1 with modifiers ""
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:413)
	at org.eclipse.yasson.internal.ReflectionUtils.lambda$createNoArgConstructorInstance$1(ReflectionUtils.java:189)
	... 10 more

```

**Comment by m0mus** [comment]
There is an error in the sample code. It must be getClass().getGenericSuperclass();
I fixed it.
