### ISSUE TITLE
Stackoverflow Error

### ISSUE THREAD

**Issue by jShiwaniGupta** [eclipse/yasson#40]
Hi,

I am getting stackoverflow error in following scenario : 
Data saved using JPA(Eclipselink) and after the server restart, if data is fetched then greeting the stackoverflow error.

Stacktrace : 
```
2017-09-04T17:30:08.996971377Z java.lang.StackOverflowError
2017-09-04T17:30:08.996984815Z 	at sun.util.locale.StringTokenIterator.nextDelimiter(StringTokenIterator.java:109)
2017-09-04T17:30:08.997050159Z 	at sun.util.locale.StringTokenIterator.setStart(StringTokenIterator.java:96)
2017-09-04T17:30:08.997066663Z 	at sun.util.locale.StringTokenIterator.<init>(StringTokenIterator.java:50)
2017-09-04T17:30:08.997096277Z 	at sun.util.locale.LanguageTag.parse(LanguageTag.java:196)
2017-09-04T17:30:08.997107668Z 	at java.util.Locale.forLanguageTag(Locale.java:1568)
2017-09-04T17:30:08.997138290Z 	at org.eclipse.yasson.internal.JsonbConfigProperties.getLocale(JsonbConfigProperties.java:216)
2017-09-04T17:30:08.997150572Z 	at org.eclipse.yasson.internal.serializer.AbstractDateTimeSerializer.toJson(AbstractDateTimeSerializer.java:77)
2017-09-04T17:30:08.997179518Z 	at org.eclipse.yasson.internal.serializer.AbstractDateTimeSerializer.serialize(AbstractDateTimeSerializer.java:54)
2017-09-04T17:30:08.997190777Z 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:91)
2017-09-04T17:30:08.997220518Z 	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:85)
2017-09-04T17:30:08.997231723Z 	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:59)
2017-09-04T17:30:08.997274067Z 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:60)
2017-09-04T17:30:08.999246301Z 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:91)
2017-09-04T17:30:08.999365846Z 	at org.eclipse.yasson.internal.serializer.CollectionSerializer.serializeInternal(CollectionSerializer.java:76)
2017-09-04T17:30:08.999382542Z 	at org.eclipse.yasson.internal.serializer.CollectionSerializer.serializeInternal(CollectionSerializer.java:35)
2017-09-04T17:30:08.999414631Z 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:60)
2017-09-04T17:30:08.999429115Z 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:91)
2017-09-04T17:30:08.999466913Z 	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:92)
2017-09-04T17:30:08.999478147Z 	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:59)
2017-09-04T17:30:08.999503797Z 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:60)
2017-09-04T17:30:08.999514227Z 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:91)
2017-09-04T17:30:08.999539978Z 	at org.eclipse.yasson.internal.serializer.CollectionSerializer.serializeInternal(CollectionSerializer.java:76)
2017-09-04T17:30:08.999550492Z 	at org.eclipse.yasson.internal.serializer.CollectionSerializer.serializeInternal(CollectionSerializer.java:35)
2017-09-04T17:30:08.999576241Z 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:60)
2017-09-04T17:30:08.999586752Z 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:91)
2017-09-04T17:30:08.999616181Z 	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:92)
2017-09-04T17:30:08.999626936Z 	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:59)
2017-09-04T17:30:08.999652493Z 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:60)
2017-09-04T17:30:08.999662844Z 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:91)
2017-09-04T17:30:08.999880012Z 	at org.eclipse.yasson.internal.serializer.CollectionSerializer.serializeInternal(CollectionSerializer.java:76)
2017-09-04T17:30:08.999906093Z 	at org.eclipse.yasson.internal.serializer.CollectionSerializer.serializeInternal(CollectionSerializer.java:35)
2017-09-04T17:30:08.999940652Z 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:60)
2017-09-04T17:30:08.999951916Z 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:91)
2017-09-04T17:30:08.999996590Z 	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:92)
2017-09-04T17:30:09.000010793Z 	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:59)
2017-09-04T17:30:09.000044388Z 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:60)
2017-09-04T17:30:09.000055802Z 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:91)
2017-09-04T17:30:09.000082359Z 	at org.eclipse.yasson.internal.serializer.CollectionSerializer.serializeInternal(CollectionSerializer.java:76)
2017-09-04T17:30:09.000092894Z 	at org.eclipse.yasson.internal.serializer.CollectionSerializer.serializeInternal(CollectionSerializer.java:35)
2017-09-04T17:30:09.000118355Z 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:60)
2017-09-04T17:30:09.000128790Z 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:91)
2017-09-04T17:30:09.000154230Z 	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:92)
2017-09-04T17:30:09.000164565Z 	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:59)
2017-09-04T17:30:09.000192021Z 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:60)
2017-09-04T17:30:09.000203033Z 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:91)
2017-09-04T17:30:09.000231254Z 	at org.eclipse.yasson.internal.serializer.CollectionSerializer.serializeInternal(CollectionSerializer.java:76)
2017-09-04T17:30:09.000242988Z 	at org.eclipse.yasson.internal.serializer.CollectionSerializer.serializeInternal(CollectionSerializer.java:35)
2017-09-04T17:30:09.000270208Z 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:60)
2017-09-04T17:30:09.000281476Z 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:91)
2017-09-04T17:30:09.000309369Z 	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:92)
```

**Comment by bravehorsie** [comment]
Hi @jShiwaniGupta 

Do you have bidirectional reference in you pojos? We don't check for bidirectional references in any way.

**Comment by jShiwaniGupta** [comment]
Not sure atm, as I was just playing last week with sample project, after the restart of docker container, got stackoverflow error.

**Comment by bravehorsie** [comment]
I am closing this for now, if you encounter this problem again please attach some reproducible snippet.

**Comment by bravehorsie** [comment]
Yasson doesn't handle bidirectional references. If you have class `A` with `b` field and class `B` with `a` field with their instances referencing each other you will have StackOverflowError raised.
