### ISSUE TITLE
@JsonbProperty doesn't work

### ISSUE THREAD

**Issue by redmitry** [eclipse/yasson#41]
Hello,

I found no way to make it work.

```
public class Publication {
    private String doi;
    public String getDOI() {
        return doi;
    }
    public void setDOI(String doi) {
        this.doi = doi;
    }
}
```
In private field it is ignored. If I put @JsonbProperty("doi") either on getter, setter or both I get:

```
javax.json.bind.JsonbException: Property DOI clashes with property doi by read or write name in class es.elixir.bsc.biotoolz.model.Publication.
	at org.eclipse.yasson.internal.ClassParser.checkPropertyNameClash(ClassParser.java:155)
	at org.eclipse.yasson.internal.ClassParser.parseProperties(ClassParser.java:62)
	at org.eclipse.yasson.internal.MappingContext$ParseClassModelFunction.apply(MappingContext.java:56)
	at org.eclipse.yasson.internal.MappingContext$ParseClassModelFunction.apply(MappingContext.java:37)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688)
	at org.eclipse.yasson.internal.MappingContext.getOrCreateClassModel(MappingContext.java:100)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:57)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:60)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:91)
	at org.eclipse.yasson.internal.serializer.CollectionSerializer.serializeInternal(CollectionSerializer.java:76)
	at org.eclipse.yasson.internal.serializer.CollectionSerializer.serializeInternal(CollectionSerializer.java:35)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:60)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:91)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:92)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:59)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:60)
	at org.eclipse.yasson.internal.Marshaller.serializeRoot(Marshaller.java:118)
	at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:76)
	at org.eclipse.yasson.internal.JsonBinding.toJson(JsonBinding.java:98)
	at es.elixir.bsc.biotoolz.model.ModelTest.testJSOB(ModelTest.java:61)
	...
```
I use yasson 1.0 from maven repository.
Thank you.

**Comment by bravehorsie** [comment]
Thanks @redmitry , will take a look,
As a workaround you can rename access methods to getDoi() setDoi().

**Comment by redmitry** [comment]
Yeah. 
It looks like clashes with default property naming strategy.

Thank you very much.
