### ISSUE TITLE
Can not serialize generic collection wrapped in generic class

### ISSUE THREAD

**Issue by stjepano** [eclipse/yasson#61]
When trying to serialize a generic collection in generic class like this:

```
public class CollectionWrapper<T> {

    private Collection<T> data;

    // default constructor, data constructors, getters, setters ...
}

// ...

Jsonb jsonb = JsonbBuilder.create();
CollectionWrapper<String> collectionWrapper = new CollectionWrapper<>(Collections.emptyList());
// or following ...
// CollectionWrapper<String> collectionWrapper = new CollectionWrapper<>(new ArrayList<>());
// CollectionWrapper<String> collectionWrapper = new CollectionWrapper<>(Arrays.asList("itemA", "itemB"));
String json = jsonb.toJson(collectionWrapper);
````

throws an exception:

```
Oct 26, 2017 5:13:54 PM org.eclipse.yasson.internal.Marshaller marshall
SEVERE: Generating incomplete JSON

java.lang.IllegalStateException: Generic bound not found for type T declared in class com.stjepano.bugs.yasson.CollectionWrapper.

	at org.eclipse.yasson.internal.ReflectionUtils.resolveTypeArguments(ReflectionUtils.java:166)
	at org.eclipse.yasson.internal.ReflectionUtils.resolveType(ReflectionUtils.java:109)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:88)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:59)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:60)
	at org.eclipse.yasson.internal.Marshaller.serializeRoot(Marshaller.java:118)
	at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:76)
	at org.eclipse.yasson.internal.JsonBinding.toJson(JsonBinding.java:98)
	at com.stjepano.bugs.yasson.JsonbTest.shouldBeAbleToSerializeGenericCollectionWrapperWithSomeItems(JsonbTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	...
```

Was expecting to get `{data:[]}`

It works if I provide runtimeType like this:

```
String json = jsonb.toJson(collectionWrapper, new CollectionWrapper<String>() {}.getClass().getGenericSuperclass());
```

but still this seems as a bug

Java:
```
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
```

Dependencies:

```
    // https://mvnrepository.com/artifact/org.eclipse/yasson
    compile group: 'org.eclipse', name: 'yasson', version: '1.0'
    // https://mvnrepository.com/artifact/org.glassfish/javax.json
    compile group: 'org.glassfish', name: 'javax.json', version: '1.1'
```

Test case:

https://github.com/stjepano/yasson-generic-collection-wrapper-bug

**Comment by NeerajSachdeva** [comment]
Thanks a lot for you suggestion, it helped me get rid of this log
[12/16/20 11:18:57:960 EST] 00000134 org.eclipse.yasson.internal.ReflectionUtils W Generic bound not found for type K declared in class com.MyBlahBlahClass
[12/16/20 11:18:57:960 EST] 00000134 org.eclipse.yasson.internal.ReflectionUtils W Generic bound not found for type T declared in class com.MyBlahBlahClass

I'm gonna try if I can implement a serializer on top of this and use reflection and make this dynamic. Will share my code If I'm able to do that.
