### ISSUE TITLE
Ignore "get"/"is" methods that have arguments

### ISSUE THREAD

**Issue by codyebberson** [eclipse/yasson#63]
Example:

```java
public static class Widget {

    public String getFoo() {
        return "foo";
    }

    public String getBar(final int baz) {
        return "bar" + baz;
    }
}

@Test
public void testGetWithArgs() {
    assertEquals("{\"foo\":\"foo\"}", JsonbBuilder.create().toJson(new Widget()));
}
```

Actual:
```
java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.yasson.internal.model.GetFromGetter.internalGetValue(GetFromGetter.java:29)
	at org.eclipse.yasson.internal.model.GetValueCommand.getValue(GetValueCommand.java:34)
	at org.eclipse.yasson.internal.model.ReflectionPropagation.getValue(ReflectionPropagation.java:72)
	at org.eclipse.yasson.internal.model.PropertyModel.getValue(PropertyModel.java:253)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:78)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:59)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:60)
	at org.eclipse.yasson.internal.Marshaller.serializeRoot(Marshaller.java:119)
	at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:76)
	at org.eclipse.yasson.internal.JsonBinding.toJson(JsonBinding.java:98)
```

**Comment by m0mus** [comment]
Pull request was merged. Closing the issue.
