### ISSUE TITLE
Date marshal / unmarshal fails

### ISSUE THREAD

**Issue by jhanders34** [eclipse/yasson#68]
The JSON-B spec states:

3.5.1 java.util.Date, Calendar, GregorianCalendar
The serialization format of java.util.Date, Calendar, GregorianCalendar instances with no time
information is ISO_DATE.

If time information is present, the format is ISO_DATE_TIME.

Implementations MUST support deserialization of both ISO_DATE and ISO_DATE_TIME into
java.util.Date, Calendar and GregorianCalendar instances.

----

Presently yasson fails when trying unmarshal an ISO_DATE string.  Here is the exception that is seen when it tries to unmarshal 28-03-1955:

javax.json.bind.JsonbException: Error parsing date from value: 28-03-1955
	at org.eclipse.yasson.internal.serializer.AbstractDateTimeDeserializer.deserialize(AbstractDateTimeDeserializer.java:64)
	at org.eclipse.yasson.internal.serializer.AbstractValueTypeDeserializer.deserialize(AbstractValueTypeDeserializer.java:64)
	at org.eclipse.yasson.internal.serializer.ObjectDeserializer.deserializeNext(ObjectDeserializer.java:163)
	at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserializeInternal(AbstractContainerDeserializer.java:84)
	at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserialize(AbstractContainerDeserializer.java:60)
	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:57)
	at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:50)
	at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:45)
	at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:79)

------

Additionally yasson is having an issue with marshaling as well.  java.sql.Date does not have a time component.  As such the spec states it should use ISO_DATE format instead of ISO_DATE_TIME format when marshaling.  Here is the exception that is seen:

java.lang.UnsupportedOperationException
	at java.sql.Date.toInstant(Date.java:315)
	at org.eclipse.yasson.internal.serializer.DateTypeSerializer.formatDefault(DateTypeSerializer.java:49)
	at org.eclipse.yasson.internal.serializer.DateTypeSerializer.formatDefault(DateTypeSerializer.java:29)
	at org.eclipse.yasson.internal.serializer.AbstractDateTimeSerializer.toJson(AbstractDateTimeSerializer.java:77)
	at org.eclipse.yasson.internal.serializer.AbstractDateTimeSerializer.serialize(AbstractDateTimeSerializer.java:54)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:91)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:85)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:59)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:60)
	at org.eclipse.yasson.internal.Marshaller.serializeRoot(Marshaller.java:118)
	at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:76)
	at org.eclipse.yasson.internal.JsonBinding.toJson(JsonBinding.java:133)

The reason this exception happens is that yasson appears to be assuming that it is a java.util.Date and toInstant() will work.  Unfortunately toInstant() is not supported on java.sql.Date.

**Comment by jhanders34** [comment]
I have not tried it, but I assume java.time.LocalDate will also have this same issue since it does not include a time component.

**Comment by bravehorsie** [comment]
@jhanders34 can you please provide an example? What type are you deserializing ISO_DATE into?

**Comment by jcoronel94** [comment]
@jhanders34 Experiencing the 2nd issue as well.  I have an entity as follows (truncated for brevity). The Date here is java.util.Date. 

`@Entity 
@Table(name = "TBLACCOUNT")
public class Account implements Serializable{

	private static final long serialVersionUID = -8039686696076337053L;

	@Id
	@GeneratedValue(generator = "account_sequence", strategy=GenerationType.SEQUENCE)
	@SequenceGenerator(name="account_sequence", sequenceName="TBLACCOUNT_SEQ", allocationSize=1)	
	@Column(name = "ACCOUNT_ID")
	private Long accountId; 

	@Temporal(TemporalType.DATE)
	@Column(name = "SUBMISSION_DATE")
	private Date submissionDate;` 

When rquesting this as entity as JSON I get the same exact stacktrace mentioned in the second half of the original post. Because the date cannot be serialized correctly the mashaller prints out SEVERE: Generating incomplete JSON

**Comment by jhanders34** [comment]
Here is a test that shows the problem.  Only the last test works.
```
import java.io.Serializable;
import java.time.LocalDate;

import javax.json.bind.Jsonb;

import org.eclipse.yasson.internal.JsonBindingBuilder;
import org.junit.Test;

import junit.framework.Assert;

public class YassonDateNoTimeTest {

    public static class LocalDateObj implements Serializable {
        public LocalDate date = LocalDate.now();
    }

    public static class SqlDateObj implements Serializable {
        public java.util.Date date = new java.sql.Date(System.currentTimeMillis());
    }

    @Test
    public void testMarshallSqlDate() {
        JsonBindingBuilder builder = new JsonBindingBuilder();
        Jsonb json = builder.build();
        String jsonString = json.toJson(new SqlDateObj());
        if (jsonString.contains("T")) {
            Assert.fail("JSON contains time for a non Date that doesn't include time");
        }
    }

    @Test
    public void testUnmarshallSqlDate() {
        JsonBindingBuilder builder = new JsonBindingBuilder();
        Jsonb json = builder.build();
        json.fromJson("{\"date\":\"1955-03-28\"}", SqlDateObj.class);
    }

    @Test
    public void testMarshallLocalDate() {
        JsonBindingBuilder builder = new JsonBindingBuilder();
        Jsonb json = builder.build();
        String jsonString = json.toJson(new SqlDateObj());
        if (jsonString.contains("T")) {
            Assert.fail("JSON contains time for a non Date that doesn't include time");
        }
    }

    @Test
    public void testUnmarshallLocalDate() {
        JsonBindingBuilder builder = new JsonBindingBuilder();
        Jsonb json = builder.build();
        json.fromJson("{\"date\":\"1955-03-28\"}", LocalDateObj.class);
    }
}
```

**Comment by jhanders34** [comment]
@bravehorsie based off of the test I provided above it appears that the sqlDate unmarshall scenario needs to do something similar to unmarshalling of a LocalDate object.  java.util.Date / java.sql.Date do make things a little complicated.

**Comment by bravehorsie** [comment]
Thank you! @jhanders34 
I went through the tests and LocalDate is working fine, there is just a mistype in testMarshallLocalDate() where you are passing a SqlDateObj for marshalling.

java.sql.Date did really need an update, we hadn't support for that at all. If you now have a property of a type java.sql.Date everything will work out of the box. 
If you have a property of type java.util.Date with java.sql.Date inside, marshalling will work, however if you want java.sql.Date to be unmarshalled inside, you have to declare `@JsonbTypeDeserializer(SqlDateTypeDeserializer.class)` on the property. See test class changes in pull request.

**Comment by jhanders34** [comment]
@Temporal(TemporalType.DATE)
    private java.util.Date date;

If the attribute is of type java.util.Date, but there is a @Temporal annotation defined as type DATE, can the logic be updated to handle that?  That way it doesn't need to be declared as a java.sql.Date.

**Comment by bravehorsie** [comment]
Yasson should not know anything about JPA, neither have dependency to its API. Jsonb API is what is supposed to be used when working with Yasson.
