### ISSUE TITLE
Failure to find parametrized type by 2 levels on implementation

### ISSUE THREAD

**Issue by grimly** [eclipse/yasson#69]
Consider the following code : https://gist.github.com/grimly/3127a54f1269e7b188fe39d5195f559f

I was expecting the ability to use a single interface to extend all those attribute converters out there (AttributeConverter from JPA, JsonbAdapter from JsonB) but then I ran into the following error :

```
javax.json.bind.JsonbException: Type: interface javax.json.bind.adapter.JsonbAdapter is not a parametrized type.
	at org.eclipse.yasson.internal.ReflectionUtils.findParameterizedType(ReflectionUtils.java:226)
	at org.eclipse.yasson.internal.ComponentMatcher.introspectAdapterBinding(ComponentMatcher.java:231)
	at org.eclipse.yasson.internal.AnnotationIntrospector.getAdapterBindingFromAnnotation(AnnotationIntrospector.java:208)
	at org.eclipse.yasson.internal.AnnotationIntrospector.getAdapterBinding(AnnotationIntrospector.java:203)
	at org.eclipse.yasson.internal.model.PropertyModel.getUserAdapterBinding(PropertyModel.java:120)
	at org.eclipse.yasson.internal.model.PropertyModel.introspectCustomization(PropertyModel.java:174)
	at org.eclipse.yasson.internal.model.PropertyModel.<init>(PropertyModel.java:87)
...
```

**Comment by grimly** [comment]
You may use [my branch](https://github.com/grimly/yasson/tree/adapter-with-intermediate-interface) which has a test case reproducing this behavior.
