### ISSUE TITLE
SEVERE: Generating incomplete JSON error on binding a non public inner class

### ISSUE THREAD

**Issue by moghaddam** [eclipse/yasson#7]
SEVERE: Generating incomplete JSON happens when trying to serialize an instance of a class that is defined as non public inner class. Original issue on Yasson forum is [https://www.eclipse.org/forums/index.php/t/1083501/](https://www.eclipse.org/forums/index.php/t/1083501/).

I think non public nested classes are not supposed to be supported. So it should not be a bug, but it would be better to have a more readable error.

Here is the stack trace:

```java
SEVERE: Generating incomplete JSON

javax.json.bind.JsonbException: Error getting value on: Person{name=John, weddingDate=Optional[Tue Jul 05 00:00:00 CEST 2016]}
	at org.eclipse.yasson.model.ReflectionPropagation$GetValueCommand.getValue(ReflectionPropagation.java:34)
	at org.eclipse.yasson.model.ReflectionPropagation.getValue(ReflectionPropagation.java:98)
	at org.eclipse.yasson.model.PropertyModel.getValue(PropertyModel.java:177)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:66)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:49)
	at org.eclipse.yasson.internal.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:52)
	at org.eclipse.yasson.internal.Marshaller.serializeRoot(Marshaller.java:104)
	at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:73)
	at org.eclipse.yasson.internal.JsonBinding.toJson(JsonBinding.java:111)
	at org.eclipse.yasson.defaultmapping.specific.OptionalDateTest.testJohn(OptionalDateTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.IllegalAccessException: Class org.eclipse.yasson.model.ReflectionPropagation can not access a member of class org.eclipse.yasson.defaultmapping.specific.OptionalDateTest$Person with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Method.invoke(Method.java:491)
	at org.eclipse.yasson.model.ReflectionPropagation.lambda$acceptMethod$0(ReflectionPropagation.java:66)
	at org.eclipse.yasson.model.ReflectionPropagation$GetValueCommand.getValue(ReflectionPropagation.java:32)
	... 38 more
```

**Comment by m0mus** [comment]
According to the spec [3.7.1] only public and protected nested classes are supported. The exception could be more descriptive though.
