### ISSUE TITLE
Java 9 module-info.java missing cdi.api

### ISSUE THREAD

**Issue by tnn** [eclipse/yasson#71]
The [module-info.java](https://github.com/eclipse/yasson/blob/master/src/main/java/module-info.java) targeted for Java 9 is missing a `requires` clause for the `cdi.api` Java EE jmod, which when used with fx `jersey-media-json-binding` will cause an exception like:
```
Caused by: java.lang.IllegalAccessError: class org.eclipse.yasson.internal.components.JsonbComponentInstanceCreatorFactory (in module org.eclipse.yasson) cannot access class javax.enterprise.inject.spi.CDI (in module cdi.api) because module org.eclipse.yasson does not read module cdi.api
	at org.eclipse.yasson.internal.components.JsonbComponentInstanceCreatorFactory.getComponentInstanceCreator(JsonbComponentInstanceCreatorFactory.java:48) ~[yasson-1.0.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.eclipse.yasson.internal.components.InstanceCreatorFactoryHelper.lambda$getComponentInstanceCreator$0(InstanceCreatorFactoryHelper.java:33) ~[yasson-1.0.1.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.eclipse.yasson.internal.components.InstanceCreatorFactoryHelper.getComponentInstanceCreator(InstanceCreatorFactoryHelper.java:28) ~[yasson-1.0.1.jar:?]
	at org.eclipse.yasson.internal.JsonbContext.<init>(JsonbContext.java:70) ~[yasson-1.0.1.jar:?]
	at org.eclipse.yasson.internal.JsonBinding.<init>(JsonBinding.java:41) ~[yasson-1.0.1.jar:?]
	at org.eclipse.yasson.internal.JsonBindingBuilder.build(JsonBindingBuilder.java:63) ~[yasson-1.0.1.jar:?]
	at javax.json.bind.JsonbBuilder.create(JsonbBuilder.java:108) ~[javax.json.bind-api-1.0.jar:?]
```
Rendering the library unusable (it can not recover from the access permission), unless you do explicitly opens up whenever you run your application

**Comment by bravehorsie** [comment]
Thanks @tnn it should probably be "requires static cdi.api", since dependency is optional at runtime. Another consideration is that cdi-api:2.0 does not declare any module, I assume you got automatic one by putting it on module path. In that case we can't assume everyone will do the same. It is better to leave that undeclared, to give users ability to use it either from module path or classpath.
