### ISSUE TITLE
Java 9 Messages.java uses non-accessible ResourceBundle.Control

### ISSUE THREAD

**Issue by tnn** [eclipse/yasson#72]
From [ResourceBundle.java](https://docs.oracle.com/javase/9/docs/api/java/util/ResourceBundle.html):

## Resource Bundles in Named Modules

When resource bundles are deployed in named modules, the following module-specific requirements and restrictions are applied.
 - Code in a named module that calls getBundle(String, Locale) will locate resource bundles in the caller's module (caller module).
 - If resource bundles are deployed in named modules separate from the caller module, those resource bundles need to be loaded from service providers of ResourceBundleProvider. The caller module must declare "uses" and the service interface name is the concatenation of the package name of the base name, string ".spi.", the simple class name of the base name, and the string "Provider". The bundle provider modules containing resource bundles must declare "provides" with the service interface name and its implementation class name. For example, if the base name is "com.example.app.MyResources", the caller module must declare "uses com.example.app.spi.MyResourcesProvider;" and a module containing resource bundles must declare "provides com.example.app.spi.MyResourcesProvider with com.example.app.internal.MyResourcesProviderImpl;" where com.example.app.internal.MyResourcesProviderImpl is an implementation class of com.example.app.spi.MyResourcesProvider.
 - If you want to use non-standard formats in named modules, such as XML, ResourceBundleProvider needs to be used.
 - The getBundle method with a ClassLoader may not be able to find resource bundles using the given ClassLoader in named modules. The getBundle method with a Module can be used, instead.
- ResourceBundle.Control is *not supported* in named modules. If the getBundle method with a ResourceBundle.Control is called in a named module, the method will throw an UnsupportedOperationException. Any service providers of ResourceBundleControlProvider are ignored in named modules.

## Problem
When running as a Named Module on Java 9, this will throw:
```
Caused by: java.lang.UnsupportedOperationException: ResourceBundle.Control not supported in named modules
	at java.util.ResourceBundle.checkNamedModule(ResourceBundle.java:1537) ~[?:?]
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:1055) ~[?:?]
	at org.eclipse.yasson.internal.properties.Messages.getMessage(Messages.java:58) ~[yasson-1.0.2-SNAPSHOT.jar:?]
```
Causing the initialisation of the library to be unusable.

## Proposed Solution
The [Messages.java](https://github.com/eclipse/yasson/blob/master/src/main/java/org/eclipse/yasson/internal/properties/Messages.java#L63) appear to be using the UTF-8 for ensuring the underlying Properties file is read as `UTF-8` (versus the pre-Java 9 default of `iso-8859-1`). In Java 9 this is fixed in [JEP 226](http://openjdk.java.net/jeps/226). So my proposal is to make a [Multi-Release Jar](openjdk.java.net/jeps/238) for Java 9+ where `UTF8Control` is simply removed.

All tests pass when Messages use the regular (non-Control) API:
```
    public static String getMessage(MessageKeys key, Locale locale, Object... objects) {
        ResourceBundle messages = ResourceBundle.getBundle(MESSAGE_BUNDLE, locale);
        MessageFormat formatter = new MessageFormat(messages.getString(key.key));
        return formatter.format(objects);
    }
```

**Comment by m0mus** [comment]
Thanks for detailed explanation. It makes sense to me. On the other hand we would like to avoid using multi-release jars. We will think what we can do. @bravehorsie any ideas?

**Comment by tnn** [comment]
@m0mus thanks for the response and the work on trying to standardizing json annotations. 
However, given the response on a few other PRs/issued and the lack on response on this, we had to find another solution. We have removed javax.json.bind from our code base, it was simply faster to switch it out with jackson than trying to fix. Given our current problems with jaxb-(api|runtime) - it's not possible to run in a acceptable state with 2.3.0 and run a 2.3.1-SNAPSHOT; we'll work on ripping it out where possible.
We don't want to hold back upgrading Java to ~1 year after GA on every release, because of libraries.

**Comment by bstansberry** [comment]
Is UTF8Control necessary? Is people somehow bringing a localized variant of yasson-messages.properties something that yasson wants to support? Otherwise AFAICT the only content of the file that needs UTF-8 are the czechDiacritics and russianDiacritics properties, which are only used by org.eclipse.yasson.customization.EncodingTest . And that seems to just be using that properties file as a way to get some data to use as input to a test.

**Comment by bravehorsie** [comment]
Should be doable without use of multi-release jar, since properties in named modules should be read as UTF-8 by default. I will take a look on that.
