### ISSUE TITLE
How to Integrate with JPA

### ISSUE THREAD

**Issue by swhp** [eclipse/yasson#75]
I've experience with JSON-B and Yasson on my Java EE 7 project and I'm tried to put the Jsonb annotations alongside with JPA annotations, for example something like this

```
@Entity
@Table("student")
@NamedQuery(name = Student.FIND_ALL, query = "select s from Student s")
public class Student {
    public static final String FIND_ALL = "Student.findAll";

    @JsonbTransient
    private Long id;

    @JsonbProperty("student-name")
    private String name;
}
```

When I tried to request into my endpoint I'm encounter two problem:

1. It seems the JPA properties was also serialized by Jsonb, I got my response like below.

```
{
  "serialVersionUID": null,
  "_persistence_shouldRefreshFetchGroup": null,
  "_persistence_session": null,
  "_persistence_relationshipInfo": null,
  "_persistence_primaryKey": null,
  "_persistence_listener": null,
  "_persistence_links": null,
  "_persistence_href": null,
  "_persistence_fetchGroup": null,
  "_persistence_cacheKey": null,
  "name": "Sukma",
  "FIND_ALL": null
}
```

**How could I remove the JPA properties from my response?**

2. From response above I also found that my static variable `FIND_ALL` was serialized by Jsonb, I'm tried to hide it using `@JsonbTransient` but I received `Java.lang.NullPointerException`.

**Do I need to pay attention towards variable with keywords `static` or `final` when using Jsonb annotations, like on my `FIND_ALL` variable?**

**Comment by bravehorsie** [comment]
1. There is similar [issue](https://github.com/eclipse/yasson/issues/59) considering @JsonbIgnoreProperties to be added. It may worth to consider adding @JsonbIncludeProperties.

2. You should have no issues annotating static final field with @JsonbTransient. I did so in test and did not receive any exception.

**Comment by m0mus** [comment]
static field should not be serialized. Are you using the latest version of Yasson? I remember fixing static fields bug.

**Comment by swhp** [comment]
Yes, I think have something like `@JsonbIncludeProperties` would be awesome, at least it's help to exclude another information such like the JPA like what I've encounter.

I'm using Yasson version `1.0` I thought it was the latest version, but may I know what is the latest version of Yasson that available right now?

**Comment by m0mus** [comment]
1.0.1
https://github.com/eclipse/yasson/releases

**Comment by maxencelaurent** [comment]
I got quite the same issue (with the latest version of Yasson).
It's even worse as NullPointerException is thrown while yasson tries to serialize EclipseLink related classes.

For instance, starting from an Entity, Marshaller go through a lot of EclipseLink stuff (UnitOfWorkValueHolder and so on), eventually crashing (NPE) in org.eclipse.persistence.queries.DatabaseQuery#getDefaultRedirector().


```
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.yasson.internal.model.GetFromGetter.internalGetValue(GetFromGetter.java:28)
    at org.eclipse.yasson.internal.model.GetValueCommand.getValue(GetValueCommand.java:34)
    at org.eclipse.yasson.internal.model.ReflectionPropagation.getValue(ReflectionPropagation.java:72)
    at org.eclipse.yasson.internal.model.PropertyModel.getValue(PropertyModel.java:255)
    at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:82)
    at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:63)                 <- JPAQuery#getDefaultRedirector()
    at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:64)
    at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:96)
    at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializeItem(AbstractContainerSerializer.java:134)
    at org.eclipse.yasson.internal.serializer.CollectionSerializer.serializeInternal(CollectionSerializer.java:52)
    at org.eclipse.yasson.internal.serializer.CollectionSerializer.serializeInternal(CollectionSerializer.java:31)
    at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:64)
    at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:96)
    at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:104)
    at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:63)                  <- public UnitOfWork#getJPAQueries()
    at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:64)
    at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:96)
    at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:104)                  <- protected getUnitOfWork()
    at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:63)                  <- instance of UnitOfWorkQueryValueHolder
    at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:64)
    at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:96)
    at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:104)                  <- protected WeavedAttributeValueHolderInterface _persistence_basedOn_vh
    at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:63)                  <- ** My Entity **
    at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:64)
    at org.eclipse.yasson.internal.Marshaller.serializeRoot(Marshaller.java:119)
    at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:75)
    at org.eclipse.yasson.internal.JsonBinding.toJson(JsonBinding.java:98)
    [...]
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
    at org.eclipse.persistence.queries.DatabaseQuery.getDefaultRedirector(DatabaseQuery.java:1271)
    ... 211 more
```


The really strange thing is all the _persistence_* fields generated by EclipseLink seems to be transient, private, or protected.

As I understand the spec (3.7.1 Scope and Field access strategy), such fields must been ignored.

**Comment by maxencelaurent** [comment]
Removing all those fields at parsing time solves the problem but such a change ( aa8b788fba142ae6591bccff9ab2c310820723fb) has an impact on how private field of inner classes are serialised  (see testAnnotatedPojo and testFieldVisibilityStrategy in  JsonbPropertyVisibilityStrategyTest)

**Comment by djrushon** [comment]
I am using Jersey 2.26 which includes yasson 1.0.  EclipseLink is not agree with collections.

**Comment by m0mus** [comment]
I just discussed this issue with @lukasj who is the main EclipseLink committer. Based on the information [here](https://github.com/eclipse-ee4j/eclipselink/blob/master/jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/weaving/ClassWeaver.java), all entities with weaved properties are also weaved with PersistenceWeaver marker interface. It can be used as a detection mechanism to separate weaved classes. 
We also should have some mechanism which switches on and off detection and ignoring weaved properties. It can be done by implementing a type level annotation, something like @JsonbIgnoreWeavedProperties or JsonbConfig method with similar name or both.
This functionality has to be switched off by default.
@bravehorsie, @swhp any more ideas?

**Comment by swhp** [comment]
Hi @m0mus thank you for the information and I'm agree with having properties to ignore weaved properties from JPA as the default. I believe the weaved information should not and is not necessary to expose it on REST endpoint.

**Comment by bmhm** [comment]
> static field should not be serialized. Are you using the latest version of Yasson? I remember fixing static fields bug.

While this is true, you can always use your own implementation of field visibility. Just add this annotation to your class: `@JsonVisibility(MyStaticVisibilityStrategy.class)`.

Then, implement `MyStaticVisibilityStrategy extends PropertyVisibilityStrategy`.
It has only two methods:
```java
    boolean isVisible(Field field);
    boolean isVisible(Method method);
```

Maybe this helps with JPA. But this is not a thing that yasson should provide. That would go into an extension project.
