### ISSUE TITLE
JSON-B adapters + JAX-RS 2.2 + hot-deploying = not cool

### ISSUE THREAD

**Issue by Xsylum** [eclipse/yasson#76]
### Cannot use hot-deploy with adapters

When using `JsonbTypeAdapter`, hot deploying makes the adapters unusable. Configuration is:

 - Payara 5.0.0.Alpha3 Full
 - Java EE 8: same behaviour whether using `javaee-web-api` (standalone war module) or `javaee-api` (ear application made of 1 x Ejb + N x web)
    - aiming for JAX-RS 2.2
    - using JSON-P 1.1 and JSON-B 1.0
 - Yasson dependency is not explicitly used, it seems that the implementation of Payara takes precedence
 - JPA not used
 - `JsonbTypeAdapter` have injected `@EJB`
 - Netbeans 8.2

When loading the fake database, a `@Singleton`, I successfully test if the `JsonbTypeAdapter` are working
 
### Workaround
 
 > Simply reboot the application server. There is no need to manually re-deploy first, the last hot-deploy will be taken into account.
 
---
 
## Context:

I'm comparing JSON-B 1.0 vs JSON-P 1.1 on JAX-RS 2.2. I faked entities so that JPA is not involved yet. Full source code is [here](https://github.com/Xsylum/java-ee/tree/master/jax-rs).

My simple entities look like:

**Company** ([full code link](https://github.com/Xsylum/java-ee/blob/master/jax-rs/src/main/java/com/playground/jax/rs/organisation/Company.java))
```java
@JsonbPropertyOrder(PropertyOrderStrategy.ANY)
public class Company{
    private Long id;
    private String name;
    
    @JsonbTypeAdapter(DepartmentListAdapter.class)
    private List<Department> departments;   // fake a @OneToMany relationship
    //...
}
```

**Department** ([full code link](https://github.com/Xsylum/java-ee/blob/master/jax-rs/src/main/java/com/playground/jax/rs/organisation/Department.java))
```java
@JsonbPropertyOrder(PropertyOrderStrategy.ANY)
public class Department{
    private Long id;
    private String name;
    
    @JsonbTypeAdapter(CompanyAdapter.class)
    private Company company;                // fake a @ManyToOne relationship
    // ...
}
```

## JSON-B & Adapter

To avoid circular serialization (Company -> Department -> Company) I have the following adapters:

 1. [`DepartmentListAdapter implements JsonbAdapter<List<Department>, JsonArray>`](https://github.com/Xsylum/java-ee/blob/master/jax-rs/src/main/java/com/playground/jax/rs/organisation/DepartmentListAdapter.java)
 2. [`CompanyAdapter implements JsonbAdapter<Company, Long>`](https://github.com/Xsylum/java-ee/blob/master/jax-rs/src/main/java/com/playground/jax/rs/organisation/CompanyAdapter.java)

Adapter works fine with a basic:

```java
Jsonb jsonB = JsonbBuilder.create();
jsonB.toJson(departmentsList);
```

## Errors

As said earlier, in both situation, a server reboot fixes the issue.

### Without using EJB

If I comment out the `@EJB` injection (`adaptFromJson(...)` always return `null`), a `ClassCastException` is triggered after the first hot-deploy:

 - when requesting companies list:
    > `java.lang.ClassCastException: com.playground.jax.rs.organisation.Department cannot be cast to com.playground.jax.rs.organisation.Department`
    
 - similarly, when requesting departments list:
    > `java.lang.ClassCastException: com.playground.jax.rs.organisation.Company cannot be cast to com.playground.jax.rs.organisation.Company`
    
Stacktrace is:

```
at org.eclipse.yasson.internal.serializer.AdaptedObjectSerializer.serialize(AdaptedObjectSerializer.java:103)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:91)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:85)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:59)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:60)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:91)
	at org.eclipse.yasson.internal.serializer.CollectionSerializer.serializeInternal(CollectionSerializer.java:79)
	at org.eclipse.yasson.internal.serializer.CollectionSerializer.serializeInternal(CollectionSerializer.java:35)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:60)
	at org.eclipse.yasson.internal.Marshaller.serializeRoot(Marshaller.java:118)
	at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:76)
	at org.eclipse.yasson.internal.JsonBinding.toJson(JsonBinding.java:98)
	at org.glassfish.jersey.jsonb.internal.JsonBindingProvider.writeTo(JsonBindingProvider.java:118)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:266)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:251)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:109)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:85)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1135)
```

### With EJB

Similarly, if I leave the `@EJB` injection, the error becomes

```
java.lang.IllegalArgumentException: Can not set com.playground.jax.rs.dummydata.FakeDatabase field com.playground.jax.rs.organisation.CompanyAdapter.db to com.playground.jax.rs.organisation.CompanyAdapter
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:75)
	at java.lang.reflect.Field.set(Field.java:764)
	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl._inject(InjectionManagerImpl.java:688)
	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.inject(InjectionManagerImpl.java:507)
	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.injectInstance(InjectionManagerImpl.java:170)
	at org.glassfish.weld.services.InjectionServicesImpl.aroundInject(InjectionServicesImpl.java:166)
	at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:46)
	at org.jboss.weld.injection.producer.ResourceInjector.inject(ResourceInjector.java:71)
	at org.jboss.weld.injection.producer.BasicInjectionTarget.inject(BasicInjectionTarget.java:117)
	at org.eclipse.yasson.internal.components.BeanManagerInstanceCreator.lambda$getOrCreateComponent$0(BeanManagerInstanceCreator.java:63)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.eclipse.yasson.internal.components.BeanManagerInstanceCreator.getOrCreateComponent(BeanManagerInstanceCreator.java:58)
	at org.eclipse.yasson.internal.ComponentMatcher.introspectAdapterBinding(ComponentMatcher.java:239)
	at org.eclipse.yasson.internal.AnnotationIntrospector.getAdapterBindingFromAnnotation(AnnotationIntrospector.java:208)
	at org.eclipse.yasson.internal.AnnotationIntrospector.getAdapterBinding(AnnotationIntrospector.java:203)
	at org.eclipse.yasson.internal.model.PropertyModel.getUserAdapterBinding(PropertyModel.java:120)
	at org.eclipse.yasson.internal.model.PropertyModel.introspectCustomization(PropertyModel.java:174)
	at org.eclipse.yasson.internal.model.PropertyModel.<init>(PropertyModel.java:87)
	at org.eclipse.yasson.internal.model.customization.ordering.PropertyOrdering.orderProperties(PropertyOrdering.java:70)
	at org.eclipse.yasson.internal.ClassParser.parseProperties(ClassParser.java:60)
	at org.eclipse.yasson.internal.MappingContext$ParseClassModelFunction.apply(MappingContext.java:56)
	at org.eclipse.yasson.internal.MappingContext$ParseClassModelFunction.apply(MappingContext.java:37)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.eclipse.yasson.internal.MappingContext.getOrCreateClassModel(MappingContext.java:100)
	at org.eclipse.yasson.internal.serializer.AbstractSerializerBuilder.getClassModel(AbstractSerializerBuilder.java:100)
	at org.eclipse.yasson.internal.serializer.DeserializerBuilder.build(DeserializerBuilder.java:145)
	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:56)
	at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:50)
	at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:45)
	at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:85)
	at org.glassfish.jersey.jsonb.internal.JsonBindingProvider.readFrom(JsonBindingProvider.java:99)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:257)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:236)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:73)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1091)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
	at org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:271)
	at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:97)
	at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:80)
	at org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.apply(ParamValueFactoryWithSource.java:74)
	at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:92)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:133)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
```

---

<sub>I tried to do some debug with basic `System.out.println` in a cloned `org.eclipse.yasson` but Netbeans does not like Java SE 9 so it didn't give me relevant hints</sub>

**Comment by dominikmathmann** [comment]
Maybe i am totally wrong because I use a different setup and run in a different exception message, but the behaviour in general is the same. I just add my comment here because it seems that nobody have any ideas:

I recognize that I have no problems when i use jsonb directly in my resource classes: 
```
   @GET
    public Response get1() {
        List<Talk> allTalks = this.talkRepository.findAll();
        return Response.ok(JsonbBuilder.create().toJson(allTalks)).build();
    }
```

instead of: 
```
   @GET
    public List<Talk> get2() {
       return this.talkRepository.findAll();
    }

```

(this produces an exception, sometimes, especially after redeployment) 

I try to do some debugging and found some potential initialization of jsonb with fix adapters, so I implement a jaxrs provider to produce a "clean" jsonb instance: 

```
 @Provider
@Produces(MediaType.APPLICATION_JSON)
public class JsonProvider implements ContextResolver<Jsonb> {

    @Override
    public Jsonb getContext(Class<?> type) {
        return JsonbBuilder.create();
    }

}
```


on the first view it will work without any problems for me. 

As already mentioned, I have a complete other setup but your problem was the only one i found which leads in the same direction, so maybe it will help. Whould be nice to get some information back if it worked.

**Comment by bravehorsie** [comment]
@Xsylum @dominikmathmann 
I know this is a bit outdated reply, but what classes are you redeploying?

Initialized Jsonb instance holds instances of adapters inside, and thus holds references to your adapter classes and in turn to adapted pojos. If you use hot redeploy you may end up in a situation when those referenced classes are discarded and replaced / hot redeployed by your application classloader and so causes initialized jsonb instances to use outdated references.

to visualize:
after a proper deploy YourApplicationClassLoader in Payara or whatever server references:

- `com.playground.jax.rs.organisation.Company.class#A`
- `com.playground.jax.rs.organisation.CompanyAdapter.class#A`

Than a Jsonb runtime instance is created with an instance of CompanyAdapter object inside transitively referencing both above classes.

You hit redeploy, and cause `com.playground.jax.rs.organisation.Company.class` to be reloaded by your YourAppClassLoader which now has two new classes:
- `com.playground.jax.rs.organisation.Company.class#B`
- `com.playground.jax.rs.organisation.CompanyAdapter.class#B`

But since initialized jsonb instance has cached object of an `com.playground.jax.rs.organisation.CompanyAdapter.class#A` it hits 

java.lang.ClassCastException: com.playground.jax.rs.organisation.Company cannot be cast to com.playground.jax.rs.organisation.Company

which basically means that `#A` version object returned by your adapter cannot be cast to `#B` version class during setting the property anymore.

If so it would also make sense why @dominikmathmann creating a new Jsonb runtime instance in every request does help for redeploying. (Don't do this in production, because you will be parsing classes with reflection on every request.)

**Comment by Xsylum** [comment]
@bravehorsie I actually redeployed `Company` class. I unfortunately moved the project out of my Github so I cannot check it but I am pretty sure about that. Your explanation actually convinced me. As it is a matter of cached object in application server, may I know for my information if the issue lies in Payara caching or Yasson caching?

Moreover, I think that I also encountered the behaviour @dominikmathmann mentioned.

**Comment by bravehorsie** [comment]
Its Yasson caching. [See here](https://github.com/eclipse-ee4j/yasson/blob/0fe80a67b33d4422f4c58a22ae539e199139f0a3/src/main/java/org/eclipse/yasson/internal/ComponentMatcher.java#L53).

**Comment by aguibert** [comment]
@bravehorsie since this issue only really exists in app server environments (where apps can be restarted while server-side components such as JAX-RS runtime can stay up and hold a reference), it seems like the responsibility of the app server to clear the JSON-B cache when a hot-update occurs.

Perhaps we could provide some sort of SPI hook that app servers could call in order to invalidate all caches? Something along the lines of:
```java
public class JsonBindingProvider extends JsonbProvider {

  private Set<Jsonb> jsonbInstances = // weak set storing all created 'Jsonb' instances

  public void clear() {
    // invoke 'Jsonb.close()' on each item in 'jsonbInstances'
  }
}
```

**Comment by bravehorsie** [comment]
We may clear the cache, but what about other user application classes that have chached jsonb instance? Should they get an invalidated exception in that case?

**Comment by bravehorsie** [comment]
Also the redeploy itself may not be related to classes used by jsonb instance.

**Comment by aguibert** [comment]
When an application server performs a hot-update of an application class, it will have to discard and re-create the application classloader, so we shouldn't have to worry about caches JSON-B instances in the application space here. 

> Also the redeploy itself may not be related to classes used by jsonb instance.

True, but "better safe than sorry" here.  If we clear the cache when it is not needed, the extra processing time will not be noticeable to the developer (<100ms impact probably).  On the contrary, if we don't clear the cache, the developer could spend hours debugging what went wrong and once they find out it was a hot-deploy issue they will probably stop using hot-deploys all-together and just re-start everything on every code change as a precaution.

**Comment by bravehorsie** [comment]
> When an application server performs a hot-update of an application class, it will have to discard and re-create the application classloader, so we shouldn't have to worry about caches JSON-B instances in the application space here.

I am a bit confused here. Are we talking about hot swap or hot redeploy? If it is the latter than is it correct that whole application state is dropped upon redeploy? If so, all jsonb instances with cached components for that application should also be dropped..

**Comment by bravehorsie** [comment]
@aguibert If we are talking about hot swap I don't know a way to drop the cache, if it is hot redeploy it should drop automatically by dropping all jsonb instances in the redeployed application.

Unfortunately @Xsylum user has been deleted and we have no other input to confirm.

**Comment by Al-un** [comment]
@bravehorsie My bad, this is my new account (I merged @Xsylum user with this one). I did not know that it also deleted my comments.

I am not sure what you meant by _hot swap_ as I only know the term in infrastructure context. In my situation, it was a _hot deploy_:

1. Change something in a class
2. Application with the updated class is deployed on the application server upon saving

As for the application state between two hot deploys, my understanding is that it depends on the application server configuration. Under GlassFish-like servers, we used [`keep-state`](https://docs.oracle.com/cd/E18930_01/html/821-2417/gkhtr.html) to maintain sessions stuff across hot deploy. It prevented us to redo manual actions such as "adding an item to the cart".

**Comment by bravehorsie** [comment]
@Al-un by [_hot swap_](https://docs.oracle.com/javase/8/docs/technotes/guides/jpda/enhancements1.4.html#hotswap) I mean a JVM class updating in debug mode, but that should not cause a ClassCastException.

Can you track where jsonb instance is referenced in your application and if that component is kept upon redeploy? Do you have direct reference to jsonb in any of your classes, or is it used in your third party dependency such is JAX-RS?

**Comment by Al-un** [comment]
Unfortunately, as I stopped Java for a while, I do not maintain this code anymore. For what it's worth, you can find it here: https://github.com/Al-un/playground/tree/master/javaee/playground-ejb/src/main/java/com/playground/organisation. It's a bit messy though... 😭 

Moreover, I am not sure if I am able to answer your question: what do you mean by reference? Entities are indeed used by JAX-RS but it is via EJB: JPA EJB "fetch" entities (is it the reference you are talking about?) and then JAX-RS EJB requires entities from JPA EJB.

**Comment by bravehorsie** [comment]
"By reference" I mean what holds a jsonb instance.
When you want to use jsonb you do some of ```Jsonb jsonb = JsonBuilder.create();```, than you  should store somewhere this instance to be accessed later. For example Jersey should hold jsonb instance for each deployed application, to reuse it for processing REST requests.

It may worth a try to inspect the lifecycle of jsonb instance in Jersey on application server.
