### ISSUE TITLE
NPE in AnnotationIntrospector

### ISSUE THREAD

**Issue by aguibert** [eclipse/yasson#95]
I am attempting to convert the following class to a JSON object:

```java
public class GameBoard {

    @JsonbTransient
    public boolean[][] board = new boolean[BOARD_SIZE][BOARD_SIZE];

    public final Set<Obstacle> obstacles = new HashSet<>();
    public final Set<Player> players = new HashSet<>();

    ...
}
```

This fails with the following exception:
```

[2/14/18 9:09:55:698 CST] 0000001c org.eclipse.yasson.internal.Marshaller                       E Generating incomplete JSON
[2/14/18 9:09:55:699 CST] 0000001c SystemErr                                                    R java.lang.NullPointerException
[2/14/18 9:09:55:699 CST] 0000001c SystemErr                                                    R 	at org.eclipse.yasson.internal.AnnotationIntrospector.checkTransientIncompatible(AnnotationIntrospector.java:534)
[2/14/18 9:09:55:724 CST] 0000001c SystemErr                                                    R 	at org.eclipse.yasson.internal.model.PropertyModel.introspectCustomization(PropertyModel.java:155)
[2/14/18 9:09:55:725 CST] 0000001c SystemErr                                                    R 	at org.eclipse.yasson.internal.model.PropertyModel.<init>(PropertyModel.java:87)
[2/14/18 9:09:55:725 CST] 0000001c SystemErr                                                    R 	at org.eclipse.yasson.internal.model.customization.ordering.PropertyOrdering.lambda$orderProperties$0(PropertyOrdering.java:79)
[2/14/18 9:09:55:725 CST] 0000001c SystemErr                                                    R 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[2/14/18 9:09:55:725 CST] 0000001c SystemErr                                                    R 	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620)
[2/14/18 9:09:55:726 CST] 0000001c SystemErr                                                    R 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
[2/14/18 9:09:55:726 CST] 0000001c SystemErr                                                    R 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[2/14/18 9:09:55:726 CST] 0000001c SystemErr                                                    R 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[2/14/18 9:09:55:726 CST] 0000001c SystemErr                                                    R 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[2/14/18 9:09:55:727 CST] 0000001c SystemErr                                                    R 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[2/14/18 9:09:55:727 CST] 0000001c SystemErr                                                    R 	at org.eclipse.yasson.internal.model.customization.ordering.PropertyOrdering.orderProperties(PropertyOrdering.java:80)
[2/14/18 9:09:55:727 CST] 0000001c SystemErr                                                    R 	at org.eclipse.yasson.internal.ClassParser.parseProperties(ClassParser.java:60)
[2/14/18 9:09:55:727 CST] 0000001c SystemErr                                                    R 	at org.eclipse.yasson.internal.MappingContext$ParseClassModelFunction.apply(MappingContext.java:56)
[2/14/18 9:09:55:727 CST] 0000001c SystemErr                                                    R 	at org.eclipse.yasson.internal.MappingContext$ParseClassModelFunction.apply(MappingContext.java:37)
[2/14/18 9:09:55:728 CST] 0000001c SystemErr                                                    R 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
[2/14/18 9:09:55:728 CST] 0000001c SystemErr                                                    R 	at org.eclipse.yasson.internal.MappingContext.getOrCreateClassModel(MappingContext.java:100)
[2/14/18 9:09:55:728 CST] 0000001c SystemErr                                                    R 	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:57)
[2/14/18 9:09:55:728 CST] 0000001c SystemErr                                                    R 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:60)
[2/14/18 9:09:55:728 CST] 0000001c SystemErr                                                    R 	at org.eclipse.yasson.internal.Marshaller.serializeRoot(Marshaller.java:118)
[2/14/18 9:09:55:729 CST] 0000001c SystemErr                                                    R 	at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:76)
[2/14/18 9:09:55:729 CST] 0000001c SystemErr                                                    R 	at org.eclipse.yasson.internal.JsonBinding.toJson(JsonBinding.java:98)
[2/14/18 9:09:55:729 CST] 0000001c SystemErr                                                    R 	at org.libertybikes.game.core.GameRound.addSpectator(GameRound.java:113)
[2/14/18 9:09:55:729 CST] 0000001c SystemErr                                                    R 	at org.libertybikes.game.core.GameRound.handleMessage(GameRound.java:96)
[2/14/18 9:09:55:729 CST] 0000001c SystemErr                                                    R 	at org.libertybikes.game.round.service.GameRoundWebsocket.onMessage(GameRoundWebsocket.java:62)
[2/14/18 9:09:55:730 CST] 0000001c SystemErr                                                    R 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2/14/18 9:09:55:730 CST] 0000001c SystemErr                                                    R 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2/14/18 9:09:55:730 CST] 0000001c SystemErr                                                    R 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2/14/18 9:09:55:730 CST] 0000001c SystemErr                                                    R 	at java.lang.reflect.Method.invoke(Method.java:498)
[2/14/18 9:09:55:731 CST] 0000001c SystemErr                                                    R 	at com.ibm.ws.wsoc.LinkRead.callOnMessage(LinkRead.java:1127)
[2/14/18 9:09:55:731 CST] 0000001c SystemErr                                                    R 	at com.ibm.ws.wsoc.LinkRead.processOnMessageTextAnnotation(LinkRead.java:981)
[2/14/18 9:09:55:731 CST] 0000001c SystemErr                                                    R 	at com.ibm.ws.wsoc.LinkRead.processRead(LinkRead.java:306)
[2/14/18 9:09:55:731 CST] 0000001c SystemErr                                                    R 	at com.ibm.ws.wsoc.WsocConnLink.processRead(WsocConnLink.java:990)
[2/14/18 9:09:55:731 CST] 0000001c SystemErr                                                    R 	at com.ibm.ws.wsoc.WsocReadCallback.completeLogic(WsocReadCallback.java:61)
[2/14/18 9:09:55:731 CST] 0000001c SystemErr                                                    R 	at com.ibm.ws.wsoc.WsocReadCallback.complete(WsocReadCallback.java:47)
[2/14/18 9:09:55:732 CST] 0000001c SystemErr                                                    R 	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:501)
[2/14/18 9:09:55:732 CST] 0000001c SystemErr                                                    R 	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:571)
[2/14/18 9:09:55:732 CST] 0000001c SystemErr                                                    R 	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:926)
[2/14/18 9:09:55:732 CST] 0000001c SystemErr                                                    R 	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1015)
[2/14/18 9:09:55:732 CST] 0000001c SystemErr                                                    R 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[2/14/18 9:09:55:732 CST] 0000001c SystemErr                                                    R 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[2/14/18 9:09:55:732 CST] 0000001c SystemErr                                                    R 	at java.lang.Thread.run(Thread.java:745)
```

Still digging into what caused this so I can provide a more detailed explanation, but at the very least we should not be getting NPEs out of Yasson code with poor error messages like this.  Need to be more descriptive on what the user may have done wrong and how the issue can be fixed.

**Comment by aguibert** [comment]
Looks like the culprit was the `board` attribute.

This issue was discovered on an OpenLiberty beta, which uses yasson 1.0.  It looks like this issue has been fixed in version 1.0.1, so I'm going to cancel this issue.
