### ISSUE TITLE
java.lang.IllegalArgumentException: wrong number of arguments on getter

### ISSUE THREAD

**Issue by maxencelaurent** [eclipse/yasson#97]
Given a very simple class like

```
public class Dummy {
    private String name;

    public String getName(){
        return name;
    }

    public String getNameWithSuffix(String suffix){
        return this.getName() + suffix;
    }
}
```
java.lang.IllegalArgumentException is thrown during the serialisation because getNameWithSuffix(String) is seen has a getter and is invoked without any argument.
```
java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.yasson.internal.model.GetFromGetter.internalGetValue(GetFromGetter.java:28)
	at org.eclipse.yasson.internal.model.GetValueCommand.getValue(GetValueCommand.java:34)
	at org.eclipse.yasson.internal.model.ReflectionPropagation.getValue(ReflectionPropagation.java:72)
```

I can easily update my code to fix this issue (rename the method or annotate it with @JsonbTransient), but such a method should not be seen as a getter at all.

**Comment by bravehorsie** [comment]
Thanks @maxencelaurent 
This is duplicate for #63 and is already fixed in master.
